-- LV2 가격대 별 상품 개수 구하기
SELECT (price div 10000) * 10000 AS PRICE_GROUP, COUNT(PRICE) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE
ORDER BY PRICE ASC

-- LV3 조건에 맞는 사용자와 총 거래금액 조회하기
SELECT USER.USER_ID, USER.NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_USER AS USER
ON BOARD.WRITER_ID = USER.USER_ID
WHERE BOARD.STATUS = "DONE"
GROUP BY USER.USER_ID
HAVING SUM(BOARD.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC

-- LV3 카테고리 별 도서 판매량 집계하기
SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK AS BOOK
JOIN BOOK_SALES AS BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01%'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY ASC

-- LV3 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT CAR_ID,  CASE
    WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
