-- 자동차 대여 기록에서 장기/단기 대여 구분하기
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
CASE WHEN TIMESTAMPDIFF(day, START_DATE, END_DATE) >= 30 THEN '장기 대여' ELSE '단기 대여'
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE date(START_DATE) between '2022-09-01' and '2022-09-30'
ORDER BY history_id DESC

-- 조건에 부합하는 중고거래 댓글 조회하기
SELECT board.TITLE, board.BOARD_ID, reply.REPLY_ID, reply.WRITER_ID, reply.CONTENTS, DATE_FORMAT(reply.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS board
JOIN USED_GOODS_REPLY AS reply
ON board.BOARD_ID = reply.BOARD_ID
WHERE date(board.CREATED_DATE) between '2022-10-01' and '2022-10-31'
ORDER BY reply.CREATED_DATE ASC, board.TITLE

-- 입양 시각 구하기(1)
SELECT
    HOUR(DATETIME) AS HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR ASC

-- 진료과별 총 예약 횟수 출력하기
SELECT MCDP_CD AS 진료과코드, COUNT(PT_NO) AS 5월예약건수
FROM APPOINTMENT
WHERE APNT_YMD like '2022-05%'
GROUP BY MCDP_CD
ORDER BY 5월예약건수 ASC, 진료과코드

-- 성분으로 구분한 아이스크림 총 주문량
SELECT ICECREAM_INFO.INGREDIENT_TYPE, SUM(ICECREAM_INFO.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FIRST_HALF
JOIN ICECREAM_INFO AS ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
GROUP BY ICECREAM_INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
